### ISSUE TITLE
How to record a resource ?

### ISSUE THREAD

**Issue by fluidlog** [Open-Initiative/LDP-framework#4]
When we use save() function :
todo = {assignee:assignee_uri, label: label}
window.storetodo.save(data);

The store is represented by literals : 
<uri> http://openinitiative.com/owl/todos#assignee "https://localhost:8443/2013/people/d74d347109" ;
Whereas "resource" notation : 
<uri> http://openinitiative.com/owl/todos#assignee https://localhost:8443/2013/people/d74d347109 ;

**Comment by sylvainlb** [comment]
I guess you should probably set your resource in the id of a blank node to avoid any confusion:
`todo = {assignee: { "@id": assignee_uri}, label: label}`
Let me know if that works.

**Comment by fluidlog** [comment]
ok, I will try that... :)
