### ISSUE TITLE
Accept contentType application/ld+json; charset=utf-8

### ISSUE THREAD

**Issue by fluidlog** [Open-Initiative/LDP-framework#9]
When get function (line 34469 of mystore.js) receive a content with a contentType " application/ld+json; charset=utf-8 ", it returns a "texte/turtle" contentType, and wait for a turtle content in spite of json-ld.

see line 29471 : self.graph = function (iri, callback, options) {...}

to accept "charset=utf-8".

thanks ! :)

**Comment by sylvainlb** [comment]
Upstream bug fixed
